# Generated by Django 5.2 on 2025-05-07 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourpakage',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
