# Generated by Django 5.2 on 2025-05-11 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourpakage',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tourpakage',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tourpakage',
            name='location',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='tourpakage',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
