# Generated by Django 5.2 on 2025-05-15 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0006_tourpakage_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourpakage',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
